[project]
name = "dk_results"
version = "0.1.0"
description = ""
requires-python = ">=3.12"

dependencies = [
    "google-api-python-client",
    "pytz",
    "requests",
    "pulp",
    "rookiepy",
    "pyyaml",
    "dotenv",
    "discord",
    "dfs-common"
]

[tool.setuptools.packages.find]
include = ["bot", "classes"]

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
    "pytest-cov"
]
lint = [
    "ruff"
]
type = [
    "ty"
]

[tool.pip]
allow-prereleases = true

[tool.uv]
default-groups = "all"

[tool.uv.sources]
dfs-common = { path = "../dfs_common" }
